import { Startup } from "./types";

export const FALLBACK_STARTUPS: Startup[] = [
  {
    name: "Neuralink",
    tagline: "Developing ultra-high bandwidth brain-machine interfaces.",
    city: "San Francisco",
    country: "USA",
    industry: "Health",
    logo: "https://logo.clearbit.com/neuralink.com",
    lat: 37.7749,
    lng: -122.4194,
    founder_quote: "We are building the future of human-computer interaction.",
    founding_year: 2016
  },
  {
    name: "OpenAI",
    tagline: "Ensuring that artificial general intelligence benefits all of humanity.",
    city: "San Francisco",
    country: "USA",
    industry: "AI",
    logo: "https://logo.clearbit.com/openai.com",
    lat: 37.7749,
    lng: -122.4194,
    founder_quote: "AGI is coming, and we must ensure it is safe and beneficial.",
    founding_year: 2015
  },
  {
    name: "Stripe",
    tagline: "Financial infrastructure for the internet.",
    city: "Dublin",
    country: "Ireland",
    industry: "Fintech",
    logo: "https://logo.clearbit.com/stripe.com",
    lat: 53.3498,
    lng: -6.2603,
    founder_quote: "Our mission is to increase the GDP of the internet.",
    founding_year: 2010
  },
  {
    name: "Mistral AI",
    tagline: "Frontier AI in your hands.",
    city: "Paris",
    country: "France",
    industry: "AI",
    logo: "https://logo.clearbit.com/mistral.ai",
    lat: 48.8566,
    lng: 2.3522,
    founder_quote: "Open weights are the future of AI development.",
    founding_year: 2023
  },
  {
    name: "Razorpay",
    tagline: "The future of payments in India.",
    city: "Bangalore",
    country: "India",
    industry: "Fintech",
    logo: "https://logo.clearbit.com/razorpay.com",
    lat: 12.9716,
    lng: 77.5946,
    founder_quote: "We are digitizing the Indian economy, one transaction at a time.",
    founding_year: 2014
  },
  {
    name: "Canva",
    tagline: "Empowering the world to design.",
    city: "Sydney",
    country: "Australia",
    industry: "SaaS",
    logo: "https://logo.clearbit.com/canva.com",
    lat: -33.8688,
    lng: 151.2093,
    founder_quote: "Design should be accessible to everyone, everywhere.",
    founding_year: 2013
  },
  {
    name: "Nubank",
    tagline: "The future of banking in Latin America.",
    city: "Sao Paulo",
    country: "Brazil",
    industry: "Fintech",
    logo: "https://logo.clearbit.com/nubank.com.br",
    lat: -23.5505,
    lng: -46.6333,
    founder_quote: "We are fighting complexity to empower people.",
    founding_year: 2013
  },
  {
    name: "DeepL",
    tagline: "The world's most accurate translator.",
    city: "Cologne",
    country: "Germany",
    industry: "AI",
    logo: "https://logo.clearbit.com/deepl.com",
    lat: 50.9375,
    lng: 6.9603,
    founder_quote: "Language barriers should be a thing of the past.",
    founding_year: 2017
  },
  {
    name: "Wise",
    tagline: "Money without borders.",
    city: "London",
    country: "UK",
    industry: "Fintech",
    logo: "https://logo.clearbit.com/wise.com",
    lat: 51.5074,
    lng: -0.1278,
    founder_quote: "Sending money abroad should be as cheap as sending an email.",
    founding_year: 2011
  },
  {
    name: "Zomato",
    tagline: "Better food for more people.",
    city: "Gurgaon",
    country: "India",
    industry: "Consumer",
    logo: "https://logo.clearbit.com/zomato.com",
    lat: 28.4595,
    lng: 77.0266,
    founder_quote: "We are building the future of food delivery.",
    founding_year: 2008
  },
  {
    name: "Climeworks",
    tagline: "Capturing CO2 from air.",
    city: "Zurich",
    country: "Switzerland",
    industry: "Climate",
    logo: "https://logo.clearbit.com/climeworks.com",
    lat: 47.3769,
    lng: 8.5417,
    founder_quote: "Direct air capture is essential for a net-zero future.",
    founding_year: 2009
  },
  {
    name: "Spotify",
    tagline: "Music for everyone.",
    city: "Stockholm",
    country: "Sweden",
    industry: "Consumer",
    logo: "https://logo.clearbit.com/spotify.com",
    lat: 59.3293,
    lng: 18.0686,
    founder_quote: "We want to unlock the potential of human creativity.",
    founding_year: 2006
  },
  {
    name: "Airbnb",
    tagline: "Belong anywhere.",
    city: "San Francisco",
    country: "USA",
    industry: "Consumer",
    logo: "https://logo.clearbit.com/airbnb.com",
    lat: 37.7749,
    lng: -122.4194,
    founder_quote: "We are building a world where anyone can belong anywhere.",
    founding_year: 2008
  },
  {
    name: "Slack",
    tagline: "Where work happens.",
    city: "San Francisco",
    country: "USA",
    industry: "SaaS",
    logo: "https://logo.clearbit.com/slack.com",
    lat: 37.7749,
    lng: -122.4194,
    founder_quote: "Making work life simpler, more pleasant and more productive.",
    founding_year: 2009
  },
  {
    name: "Revolut",
    tagline: "One app, all things money.",
    city: "London",
    country: "UK",
    industry: "Fintech",
    logo: "https://logo.clearbit.com/revolut.com",
    lat: 51.5074,
    lng: -0.1278,
    founder_quote: "We are building the world's first truly global financial super app.",
    founding_year: 2015
  },
  {
    name: "Klarna",
    tagline: "Smoooth payments.",
    city: "Stockholm",
    country: "Sweden",
    industry: "Fintech",
    logo: "https://logo.clearbit.com/klarna.com",
    lat: 59.3293,
    lng: 18.0686,
    founder_quote: "We want to make shopping smoooth.",
    founding_year: 2005
  },
  {
    name: "Bolt",
    tagline: "The future of urban transport.",
    city: "Tallinn",
    country: "Estonia",
    industry: "Consumer",
    logo: "https://logo.clearbit.com/bolt.eu",
    lat: 59.4370,
    lng: 24.7536,
    founder_quote: "We are building cities for people, not cars.",
    founding_year: 2013
  },
  {
    name: "UiPath",
    tagline: "The foundation of the automated enterprise.",
    city: "New York",
    country: "USA",
    industry: "SaaS",
    logo: "https://logo.clearbit.com/uipath.com",
    lat: 40.7128,
    lng: -74.0060,
    founder_quote: "A robot for every person.",
    founding_year: 2005
  },
  {
    name: "Adyen",
    tagline: "The payments platform of choice for the world's leading companies.",
    city: "Amsterdam",
    country: "Netherlands",
    industry: "Fintech",
    logo: "https://logo.clearbit.com/adyen.com",
    lat: 52.3676,
    lng: 4.9041,
    founder_quote: "We focus on building for the long term.",
    founding_year: 2006
  },
  {
    name: "Grab",
    tagline: "The everyday everything app.",
    city: "Singapore",
    country: "Singapore",
    industry: "Consumer",
    logo: "https://logo.clearbit.com/grab.com",
    lat: 1.3521,
    lng: 103.8198,
    founder_quote: "We are driving Southeast Asia forward.",
    founding_year: 2012
  },
  {
    name: "Gojek",
    tagline: "Flow with Gojek.",
    city: "Jakarta",
    country: "Indonesia",
    industry: "Consumer",
    logo: "https://logo.clearbit.com/gojek.com",
    lat: -6.2088,
    lng: 106.8456,
    founder_quote: "Solving daily friction with technology.",
    founding_year: 2010
  },
  {
    name: "Mercado Libre",
    tagline: "The leading e-commerce platform in Latin America.",
    city: "Buenos Aires",
    country: "Argentina",
    industry: "Consumer",
    logo: "https://logo.clearbit.com/mercadolibre.com",
    lat: -34.6037,
    lng: -58.3816,
    founder_quote: "Democratizing commerce and payments in Latin America.",
    founding_year: 1999
  },
  {
    name: "Rappi",
    tagline: "The super-app of Latin America.",
    city: "Bogota",
    country: "Colombia",
    industry: "Consumer",
    logo: "https://logo.clearbit.com/rappi.com",
    lat: 4.7110,
    lng: -74.0721,
    founder_quote: "We are transforming the way people live in Latin America.",
    founding_year: 2015
  },
  {
    name: "Paytm",
    tagline: "India's largest digital payments platform.",
    city: "Noida",
    country: "India",
    industry: "Fintech",
    logo: "https://logo.clearbit.com/paytm.com",
    lat: 28.5355,
    lng: 77.3910,
    founder_quote: "Bringing half a billion Indians into the mainstream economy.",
    founding_year: 2010
  },
  {
    name: "Ola",
    tagline: "Moving the world.",
    city: "Bangalore",
    country: "India",
    industry: "Consumer",
    logo: "https://logo.clearbit.com/olacabs.com",
    lat: 12.9716,
    lng: 77.5946,
    founder_quote: "Building a sustainable future for mobility.",
    founding_year: 2010
  },
  {
    name: "Byju's",
    tagline: "Fall in love with learning.",
    city: "Bangalore",
    country: "India",
    industry: "SaaS",
    logo: "https://logo.clearbit.com/byjus.com",
    lat: 12.9716,
    lng: 77.5946,
    founder_quote: "Making learning more visual and engaging.",
    founding_year: 2011
  },
  {
    name: "Checkout.com",
    tagline: "The connected payments platform.",
    city: "London",
    country: "UK",
    industry: "Fintech",
    logo: "https://logo.clearbit.com/checkout.com",
    lat: 51.5074,
    lng: -0.1278,
    founder_quote: "We build the technology that powers the digital economy.",
    founding_year: 2012
  },
  {
    name: "Celonis",
    tagline: "The global leader in execution management.",
    city: "Munich",
    country: "Germany",
    industry: "SaaS",
    logo: "https://logo.clearbit.com/celonis.com",
    lat: 48.1351,
    lng: 11.5820,
    founder_quote: "Unlocking the value in your business processes.",
    founding_year: 2011
  },
  {
    name: "Personio",
    tagline: "The HR operating system for SMEs.",
    city: "Munich",
    country: "Germany",
    industry: "SaaS",
    logo: "https://logo.clearbit.com/personio.com",
    lat: 48.1351,
    lng: 11.5820,
    founder_quote: "Enabling better organizations through better HR.",
    founding_year: 2015
  },
  {
    name: "Back Market",
    tagline: "The leading marketplace for refurbished electronics.",
    city: "Paris",
    country: "France",
    industry: "Consumer",
    logo: "https://logo.clearbit.com/backmarket.com",
    lat: 48.8566,
    lng: 2.3522,
    founder_quote: "Making refurbished the new standard.",
    founding_year: 2014
  },
  {
    name: "Sorare",
    tagline: "The global fantasy football game.",
    city: "Paris",
    country: "France",
    industry: "Consumer",
    logo: "https://logo.clearbit.com/sorare.com",
    lat: 48.8566,
    lng: 2.3522,
    founder_quote: "Connecting sports fans through digital collectibles.",
    founding_year: 2018
  },
  {
    name: "Trade Republic",
    tagline: "The future of mobile investing.",
    city: "Berlin",
    country: "Germany",
    industry: "Fintech",
    logo: "https://logo.clearbit.com/traderepublic.com",
    lat: 52.5200,
    lng: 13.4050,
    founder_quote: "Democratizing access to capital markets.",
    founding_year: 2015
  },
  {
    name: "N26",
    tagline: "The mobile bank.",
    city: "Berlin",
    country: "Germany",
    industry: "Fintech",
    logo: "https://logo.clearbit.com/n26.com",
    lat: 52.5200,
    lng: 13.4050,
    founder_quote: "Building the bank the world loves to use.",
    founding_year: 2013
  },
  {
    name: "Northvolt",
    tagline: "Building the world's greenest battery.",
    city: "Stockholm",
    country: "Sweden",
    industry: "Climate",
    logo: "https://logo.clearbit.com/northvolt.com",
    lat: 59.3293,
    lng: 18.0686,
    founder_quote: "Powering the transition to a clean energy future.",
    founding_year: 2016
  },
  {
    name: "Einride",
    tagline: "The future of freight.",
    city: "Stockholm",
    country: "Sweden",
    industry: "Climate",
    logo: "https://logo.clearbit.com/einride.tech",
    lat: 59.3293,
    lng: 18.0686,
    founder_quote: "Transforming the way the world moves goods.",
    founding_year: 2016
  },
  {
    name: "Hugging Face",
    tagline: "The AI community building the future.",
    city: "New York",
    country: "USA",
    industry: "AI",
    logo: "https://logo.clearbit.com/huggingface.co",
    lat: 40.7128,
    lng: -74.0060,
    founder_quote: "Democratizing good machine learning.",
    founding_year: 2016
  },
  {
    name: "Anthropic",
    tagline: "AI safety and research company.",
    city: "San Francisco",
    country: "USA",
    industry: "AI",
    logo: "https://logo.clearbit.com/anthropic.com",
    lat: 37.7749,
    lng: -122.4194,
    founder_quote: "Building reliable, interpretable, and steerable AI systems.",
    founding_year: 2021
  },
  {
    name: "Cohere",
    tagline: "AI for the enterprise.",
    city: "Toronto",
    country: "Canada",
    industry: "AI",
    logo: "https://logo.clearbit.com/cohere.com",
    lat: 43.6532,
    lng: -79.3832,
    founder_quote: "Empowering every developer to use NLP.",
    founding_year: 2019
  },
  {
    name: "Stability AI",
    tagline: "AI by the people, for the people.",
    city: "London",
    country: "UK",
    industry: "AI",
    logo: "https://logo.clearbit.com/stability.ai",
    lat: 51.5074,
    lng: -0.1278,
    founder_quote: "Building the foundation for open AI.",
    founding_year: 2019
  },
  {
    name: "Perplexity AI",
    tagline: "Where knowledge begins.",
    city: "San Francisco",
    country: "USA",
    industry: "AI",
    logo: "https://logo.clearbit.com/perplexity.ai",
    lat: 37.7749,
    lng: -122.4194,
    founder_quote: "Reinventing search with AI.",
    founding_year: 2022
  }
];
